import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req) {
  try {
    const { name, email, message } = await req.json();

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // --- SHARED STYLES ---
    const brandBlue = "#003366";
    const brandGold = "#C5A059";
    const bgLight = "#FDFCFB";

    // 1. ADMIN EMAIL TEMPLATE (Sleek Data Logging)
    const adminMailOptions = {
      from: `"Conference DBA System" <${process.env.EMAIL_USER}>`,
      to: process.env.EMAIL_USER,
      subject: `🔴 Alert: New Inquiry from ${name}`,
      html: `
        <div style="font-family: 'Segoe UI', Helvetica, Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; border-radius: 16px; overflow: hidden; background-color: #ffffff;">
          <div style="background-color: ${brandBlue}; padding: 30px; text-align: center;">
            <h2 style="color: #ffffff; margin: 0; text-transform: uppercase; letter-spacing: 3px; font-size: 18px;">Lead Notification</h2>
            <p style="color: ${brandGold}; margin: 5px 0 0; font-size: 12px; font-weight: bold;">CONFERENCE DBA 2026</p>
          </div>
          <div style="padding: 40px 30px;">
            <div style="margin-bottom: 25px; border-bottom: 1px solid #f0f0f0; padding-bottom: 15px;">
              <span style="font-size: 10px; color: ${brandGold}; font-weight: 900; text-transform: uppercase; tracking: 1px;">Sender Details</span>
              <p style="margin: 5px 0; color: ${brandBlue}; font-weight: bold; font-size: 16px;">Sender Name: ${name}<br> Sender Email: ${email}</p>
            </div>
            <div style="background-color: ${bgLight}; border-left: 4px solid ${brandGold}; padding: 20px; border-radius: 8px;">
              Message: <p style="margin: 0; color: #555; font-size: 14px; line-height: 1.6;">${message}</p>
            </div>
          </div>
          <div style="background-color: #f9f9f9; padding: 20px; text-align: center; font-size: 11px; color: #bbb;">
            Auto-generated by the official Conference DBA Portal.
          </div>
        </div>
      `,
    };

    // 2. USER ACKNOWLEDGEMENT (Official Website Aesthetic)
    const userMailOptions = {
      from: `"Conference DBA 2026" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: "Acknowledgment: Your Inquiry to Conference DBA 2026",
      html: `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: auto; background-color: ${bgLight}; border: 1px solid #f0f0f0; border-radius: 20px; overflow: hidden;">
          
          <div style="background-color: ${brandBlue}; padding: 40px 20px; text-align: center;">
             <h1 style="color: #ffffff; margin: 0; font-size: 22px; font-weight: 900; letter-spacing: -1px; text-transform: uppercase;">
                Conference <span style="color: ${brandGold};">DBA</span>
             </h1>
             <p style="color: rgba(255,255,255,0.5); font-size: 10px; margin-top: 5px; text-transform: uppercase; letter-spacing: 2px;">International 2026</p>
          </div>

          <div style="padding: 45px 35px; background-color: #ffffff;">
            <h2 style="color: ${brandBlue}; font-size: 20px; font-weight: 900; margin-top: 0;">Dear ${name},</h2>
            <p style="color: #555; font-size: 15px; line-height: 1.8;">
              Thank you for contacting the <strong>International Conference on Economics, Business and Technology Management (ICEBTM) 2026</strong>. 
            </p>
            <p style="color: #555; font-size: 15px; line-height: 1.8;">
              We have received your message and our organizing committee at <strong>East West University</strong> is currently reviewing your request. You can expect a response within <strong>24 to 48 hours</strong>.
            </p>

            <div style="margin-top: 35px; padding: 25px; border: 1px dashed ${brandGold}; border-radius: 15px; text-align: center;">
               <p style="margin: 0; font-size: 13px; color: ${brandBlue}; font-weight: bold; text-transform: uppercase;">Did you know?</p>
               <p style="margin: 5px 0 15px; font-size: 12px; color: #888;">The submission window for Scopus Indexed Proceedings is currently active.</p>
               <a href="https://your-website-url.com/guidelines" style="background-color: ${brandBlue}; color: #ffffff; padding: 12px 25px; border-radius: 10px; text-decoration: none; font-size: 11px; font-weight: bold; display: inline-block; text-transform: uppercase; letter-spacing: 1px;">View Guidelines</a>
            </div>

            <div style="margin-top: 40px; border-top: 1px solid #eee; pt: 25px;">
              <p style="margin: 0; font-weight: 900; color: ${brandBlue}; font-size: 14px;">Regards,</p>
              <p style="margin: 0; color: #444; font-size: 14px;">Organizing Committee</p>
              <p style="margin: 0; color: ${brandGold}; font-size: 12px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px;">Conference DBA 2026</p>
            </div>
          </div>

          <div style="background-color: ${brandBlue}; color: #ffffff; padding: 25px; text-align: center;">
            <p style="margin: 0; font-size: 9px; letter-spacing: 2px; opacity: 0.7;">EAST WEST UNIVERSITY | AFTABNAGAR, DHAKA</p>
            <div style="margin-top: 15px;">
                <a href="#" style="color: ${brandGold}; text-decoration: none; font-size: 10px; margin: 0 10px;">Privacy Policy</a>
                <a href="#" style="color: ${brandGold}; text-decoration: none; font-size: 10px; margin: 0 10px;">Contact Us</a>
            </div>
          </div>
        </div>
      `,
    };

    // Execute mailing
    await transporter.sendMail(adminMailOptions);
    await transporter.sendMail(userMailOptions);

    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error) {
    console.error("Mail Error:", error);
    return NextResponse.json(
      { error: "Email delivery failed" },
      { status: 500 },
    );
  }
}
